languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "nanowatts.net"
# logo = "img/logo.jpg"
# description = "Personal website and blog of Justin Watts"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2008"

[author]
  # name = "Justin Watts"
  # image = "img/author.jpg"
  # headline = "I'm only human"
  # bio = "A little bit about you"
  # links = [
  #   { email = "mailto:justin@nanowatts.net" },
  #   { link = "https://nanowatts.net" }
  #   { github = "https://github.com/nanowatts" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/nanowatts" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mas.to/@nanowatts" },
  # ]
