# netlify.toml

[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.22"
  TZ = "UTC"

[context.production.environment]
  HUGO_VERSION = "0.105.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.105.0"